[package]
name = "chat_test"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dev-dependencies]
chat_core = { workspace = true}
chat_server = { workspace = true}
notify_server = { workspace = true}
reqwest = "0.12.9"
tokio = { workspace = true }
axum = { workspace = true }
